name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup:

      - name: Checkout React app
        uses: actions/checkout@v2
        with:
          repository: millipede-guide/millipede-guide-app

      - name: Checkout content
        uses: actions/checkout@v2
        with:
          path: public/content

      - name: Look for gh-pages branch
        run: |
          cd public/content
          echo "::set-env name=REMOTE_BRANCHES::`git ls-remote --quiet --refs origin gh-pages`"
          cd -

      - name: Checkout gh-pages branch
        if: ${{ contains(env.REMOTE_BRANCHES, 'gh-pages') }}
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: out

      # Run:

      - name: Cache NPM
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: NPM Install
        run: npm ci

      - name: Cache Next.js build
        uses: actions/cache@v2
        env:
          cache-name: cache-next-build
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: ./build.sh
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}

      - name: Save document validation results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: validation-results
          path: validation-results.txt

      # Deploy:

      - name: Set CNAME
        env:
          CNAME: ${{ secrets.CNAME }}
        run: echo "$CNAME" > ./out/CNAME

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: false
